# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('availability', models.IntegerField()),
                ('imagePath', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Category')),
            ],
            options={
                'verbose_name_plural': 'drugs',
            },
        ),
    ]
