# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('friendlyName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('availability', models.IntegerField()),
                ('imagePath', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'drugs',
                'managed': False,
            },
        ),
    ]
