# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
