# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_type',
            field=models.IntegerField(choices=[(2, 'Courier'), (1, 'From Store')], default=1),
        ),
    ]
