# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170608_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(2, 'Bank Disposal'), (1, 'Cash')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_type',
            field=models.IntegerField(choices=[(1, 'From Store'), (2, 'Courier')], default=1),
        ),
    ]
