# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 17:11
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170609_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank Disposal')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_type',
            field=models.IntegerField(choices=[(2, 'Courier'), (1, 'From Store')], default=1),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
